### ISSUE TITLE
If an NPM module is not found the result of `serveless deploy` is `Successfully deployed` although there is an exception shown

### ISSUE THREAD

**Issue by jcenturion** [auth0/serverless-webtasks#6]
```
Serverless: Packaging service...
Serverless: Packaging disabled for function: "main"
Serverless: Deploying function: main...
{ Error: Cannot find module 'chai'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jcenturion/projects/wt/hackathon/temp/my-service/handler.js:3:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at getStageOption.then.error (/Users/jcenturion/projects/wt/hackathon/temp/my-service/node_modules/@webtask/serverless-webtasks/lib/shared/webtasksService.js:143:38)
    at tryCatcher (/Users/jcenturion/projects/wt/hackathon/temp/my-service/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jcenturion/projects/wt/hackathon/temp/my-service/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/jcenturion/projects/wt/hackathon/temp/my-service/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/Users/jcenturion/projects/wt/hackathon/temp/my-service/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/Users/jcenturion/projects/wt/hackathon/temp/my-service/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Users/jcenturion/projects/wt/hackathon/temp/my-service/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/jcenturion/projects/wt/hackathon/temp/my-service/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5) code: 'MODULE_NOT_FOUND' }
Serverless: Successfully deployed function: main
```

**Comment by rwtombaugh** [comment]
Should be fixed now...
